spring:
  application:
    name: rental-manager
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
    password: password
  flyway.enabled: true
  h2:
    console:
      enabled: true
  cloud:
    function:
      definition: truckBought
    stream:
      default:
        group: initiator
      bindings:
        reservation:
          destination: reservation-topic
        truckBought-in-0:
          destination: truck-availability-topic
springdoc.api-docs.path: /api-docs
