apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rental-manager
  labels:
    app.kubernetes.io/part-of: rental-manager
    apps.tanzu.vmware.com/workload-type: web
#    apps.tanzu.vmware.com/has-tests: true
#    apps.tanzu.vmware.com/supply-chain: scanning
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: base
      url: https://github.com/rabadiw/tapathon-teamb.git
